/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // MD3 Surface scale
        'background':              '#faf9f7',
        'surface':                 '#faf9f7',
        'surface-bright':          '#faf9f7',
        'surface-dim':             '#dadad8',
        'surface-variant':         '#e3e2e0',
        'surface-container-lowest':'#ffffff',
        'surface-container-low':   '#f4f4f1',
        'surface-container':       '#eeeeeb',
        'surface-container-high':  '#e8e8e6',
        'surface-container-highest':'#e3e2e0',
        // MD3 On-surface
        'on-surface':              '#1a1c1b',
        'on-surface-variant':      '#414845',
        'inverse-surface':         '#2f312f',
        'inverse-on-surface':      '#f1f1ee',
        // MD3 Primary (dark sage)
        'primary':                 '#456558',
        'on-primary':              '#ffffff',
        'primary-container':       '#7c9e8f',
        'on-primary-container':    '#14352a',
        'primary-fixed':           '#c7ebda',
        'primary-fixed-dim':       '#abcebe',
        'on-primary-fixed':        '#002117',
        'on-primary-fixed-variant':'#2d4d41',
        'inverse-primary':         '#abcebe',
        'surface-tint':            '#456558',
        // MD3 Secondary (terracotta brown)
        'secondary':               '#85522d',
        'on-secondary':            '#ffffff',
        'secondary-container':     '#ffba8d',
        'on-secondary-container':  '#7a4824',
        'secondary-fixed':         '#ffdcc6',
        'secondary-fixed-dim':     '#fcb88a',
        'on-secondary-fixed':      '#311400',
        'on-secondary-fixed-variant':'#693b18',
        // MD3 Tertiary (warm red-brown)
        'tertiary':                '#7d5451',
        'on-tertiary':             '#ffffff',
        'tertiary-container':      '#bb8b88',
        'on-tertiary-container':   '#472624',
        'tertiary-fixed':          '#ffdad7',
        'tertiary-fixed-dim':      '#efbab6',
        'on-tertiary-fixed':       '#301312',
        'on-tertiary-fixed-variant':'#623d3b',
        // MD3 Outline
        'outline':                 '#727974',
        'outline-variant':         '#c1c8c3',
        // MD3 Error
        'error':                   '#ba1a1a',
        'on-error':                '#ffffff',
        'error-container':         '#ffdad6',
        'on-error-container':      '#93000a',
        // Custom brand tokens (match FRONTEND_CONTEXT.md spec)
        'sage-green':              '#7C9E8F',
        'sage-dark':               '#4A6B5E',
        'terracotta':              '#D4956A',
        'terracotta-light':        '#fdf1ea',
        'text-brown':              '#2C2417',
        'text-muted-warm':         '#B0A89E',
        'border-light':            '#E8E2D9',
        'indigo-light':            '#eef0f9',
        'custom-divider':          '#E8E2D9',
        'custom-terracotta':       '#D4956A',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:     '0.5rem',
        xl:     '0.75rem',
        '2xl':  '1.125rem',
        full:   '9999px',
        card:   '18px',
        btn:    '12px',
        input:  '10px',
      },
      spacing: {
        base:                '4px',
        xs:                  '8px',
        md:                  '16px',
        lg:                  '24px',
        xl:                  '32px',
        gutter:              '16px',
        'container-padding': '20px',
      },
      fontFamily: {
        'display':     ['DM Sans', 'sans-serif'],
        'headline-lg': ['DM Sans', 'sans-serif'],
        'headline-md': ['DM Sans', 'sans-serif'],
        'body-lg':     ['DM Sans', 'sans-serif'],
        'body-md':     ['DM Sans', 'sans-serif'],
        'body-sm':     ['DM Sans', 'sans-serif'],
        'label-caps':  ['DM Sans', 'sans-serif'],
        'serif-display':['DM Serif Display', 'serif'],
        sans:          ['DM Sans', 'sans-serif'],
      },
      fontSize: {
        'display':     ['32px', { lineHeight: '40px',  letterSpacing: '-0.02em', fontWeight: '300' }],
        'headline-lg': ['24px', { lineHeight: '32px',  fontWeight: '300' }],
        'headline-md': ['20px', { lineHeight: '28px',  fontWeight: '400' }],
        'body-lg':     ['18px', { lineHeight: '28px',  fontWeight: '400' }],
        'body-md':     ['16px', { lineHeight: '24px',  fontWeight: '400' }],
        'body-sm':     ['14px', { lineHeight: '20px',  fontWeight: '500' }],
        'label-caps':  ['12px', { lineHeight: '16px',  letterSpacing: '0.05em', fontWeight: '500' }],
        'quote':       ['19px', { lineHeight: '28px',  fontWeight: '400' }],
        'brand-wordmark': ['26px', { fontWeight: '300' }],
      },
      boxShadow: {
        warm:      '0 4px 12px rgba(44,36,23,0.06)',
        'warm-glow':'0 8px 24px rgba(44,36,23,0.08)',
        'warm-sm': '0 2px 8px rgba(44,36,23,0.05)',
      },
    },
  },
  plugins: [],
}
